from __future__ import annotations

import os

import altair as alt
import pandas as pd
import streamlit as st
from gspread import WorksheetNotFound
from streamlit_autorefresh import st_autorefresh

from main import (
    DASHBOARD_SHEET_NAME,
    FORECAST_SHEET_NAME,
    SHEET_NAME,
    SIGNALS_SHEET_NAME,
    SheetStore,
    load_history_frame,
)


st_autorefresh(interval=60 * 1000, key="data_refresh")

st.set_page_config(page_title="Buff163 Price Tracker", layout="wide")
st.title("Buff163 Price Tracker Dashboard")
st.caption("Reads Google Sheets data generated by the scheduled BUFF163 tracker.")


@st.cache_resource(show_spinner=False)
def get_store() -> SheetStore:
    return SheetStore(os.getenv("BUFF_SHEET_NAME", SHEET_NAME))


@st.cache_data(ttl=60, show_spinner=False)
def load_sheet_records(sheet_name: str) -> pd.DataFrame:
    try:
        worksheet = get_store().spreadsheet.worksheet(sheet_name)
        records = worksheet.get_all_records()
        return pd.DataFrame(records) if records else pd.DataFrame()
    except WorksheetNotFound:
        return pd.DataFrame()


history_df = load_history_frame(get_store())
dashboard_df = load_sheet_records(DASHBOARD_SHEET_NAME)
signals_df = load_sheet_records(SIGNALS_SHEET_NAME)
forecast_df = load_sheet_records(FORECAST_SHEET_NAME)

if history_df.empty:
    st.warning("No historical data found yet. Run `python main.py` or wait for GitHub Actions to write the first snapshot.")
    st.stop()

history_df["Timestamp"] = pd.to_datetime(history_df["Timestamp"], errors="coerce", utc=True)
history_df["Price"] = pd.to_numeric(history_df["Price"], errors="coerce")
history_df["Listings"] = pd.to_numeric(history_df["Listings"], errors="coerce")
history_df = history_df.dropna(subset=["Timestamp", "Skin Name", "Price"]).sort_values("Timestamp")

st.sidebar.header("Filters")
skin_list = sorted(history_df["Skin Name"].dropna().unique().tolist())
skin_selected = st.sidebar.selectbox("Select a skin", skin_list)
show_forecast = st.sidebar.checkbox("Show 7-day forecast", value=not forecast_df.empty)

filtered = history_df[history_df["Skin Name"] == skin_selected].copy()
latest = filtered.iloc[-1]

col1, col2, col3, col4 = st.columns(4)
col1.metric("Current Price", f"{latest['Price']:.2f} CNY")
col2.metric("Listings", int(latest["Listings"]) if pd.notna(latest["Listings"]) else "N/A")
col3.metric("Last Update", latest["Timestamp"].strftime("%Y-%m-%d %H:%M UTC"))

signal_value = "N/A"
if not dashboard_df.empty:
    dashboard_row = dashboard_df[dashboard_df["Skin Name"] == skin_selected]
    if not dashboard_row.empty:
        signal_value = str(dashboard_row.iloc[-1].get("Signal", "N/A"))
col4.metric("Signal", signal_value)

trend_chart = (
    alt.Chart(filtered)
    .mark_line(point=True, strokeWidth=3)
    .encode(
        x=alt.X("Timestamp:T", title="Timestamp"),
        y=alt.Y("Price:Q", title="Price (CNY)"),
        tooltip=["Timestamp:T", "Price:Q", "Listings:Q"],
    )
    .properties(height=420)
)

listing_chart = (
    alt.Chart(filtered)
    .mark_bar(opacity=0.35)
    .encode(
        x=alt.X("Timestamp:T", title="Timestamp"),
        y=alt.Y("Listings:Q", title="Listings"),
        tooltip=["Timestamp:T", "Listings:Q"],
    )
    .properties(height=140)
)

st.subheader(f"Price trend for {skin_selected}")
st.altair_chart((trend_chart & listing_chart).resolve_scale(x="shared"), use_container_width=True)

info_col, signal_col = st.columns((2, 1))
with info_col:
    st.subheader("Recent observations")
    available_columns = [
        column
        for column in ["Timestamp", "Price", "Listings", "Observed Orders"]
        if column in filtered.columns
    ]
    st.dataframe(
        filtered[available_columns].sort_values("Timestamp", ascending=False).head(10),
        use_container_width=True,
        hide_index=True,
    )

with signal_col:
    st.subheader("Agent signal")
    signal_row = pd.DataFrame()
    if not signals_df.empty:
        signal_row = signals_df[signals_df["Skin Name"] == skin_selected]
    if not signal_row.empty:
        row = signal_row.iloc[-1]
        st.metric("Recommendation", str(row["Signal"]))
        st.metric("Confidence", f"{float(row['Confidence']):.2f}")
        st.write(str(row["Rationale"]))
        st.caption(f"Based on {int(row['Data Points'])} historical points.")
    else:
        st.info("No signal generated yet for this skin.")

if show_forecast and not forecast_df.empty:
    forecast_df["Forecast Date"] = pd.to_datetime(forecast_df["Forecast Date"], errors="coerce")
    forecast_df["Predicted Price"] = pd.to_numeric(forecast_df["Predicted Price"], errors="coerce")
    selected_forecast = forecast_df[forecast_df["Skin Name"] == skin_selected].dropna()
    if not selected_forecast.empty:
        st.subheader("7-day forecast")
        forecast_chart = (
            alt.Chart(selected_forecast)
            .mark_line(point=True, color="#F97316", strokeWidth=3)
            .encode(
                x=alt.X("Forecast Date:T", title="Date"),
                y=alt.Y("Predicted Price:Q", title="Predicted Price (CNY)"),
                tooltip=["Forecast Date:T", "Predicted Price:Q"],
            )
            .properties(height=280)
        )
        st.altair_chart(forecast_chart, use_container_width=True)
