name: Run Buff Knife Tracker

on:
  schedule:
    - cron: '0 0 * * *'     # Runs at 12:00 AM UTC
    - cron: '0 12 * * *'    # Runs at 12:00 PM UTC
  workflow_dispatch:        # Allows manual run via GitHub UI

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping install."
          fi

      - name: Write credentials to file
  run: echo "${{ secrets.GSHEET_CREDS }}" > credentials.json


      - name: Run the Buff tracker
        run: python main.py
